### ISSUE TITLE
filenames incompatible with windows (colon character in timestamp)

### ISSUE THREAD

**Issue by CGYoung1040** [yozhiik/starknet-csvs#4]
**Output:**

C:\Users\user\Desktop\starknet-csvs-main>python export-starknet.py 0xabc123 transfers api_key 
Traceback (most recent call last):
  File "C:\Users\user\Desktop\starknet-csvs-main\export-starknet.py", line 127, in <module>
    with open(f_name, 'w') as csv_file:
         ^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'transfers_0xabc123 _2024-02-27 03:28:10.313219.csv'

**quick workaround: skip timestamp for the filename**

`f_name = download_type + "_" + fname_address + "_" + ".csv"`

**Comment by IanVargas** [comment]
hi @CGYoung1040  is it possible I can grab this issue? 
I think is not necessary to remove the date from the file as it could be necessary for some users, I think it would be better to do some changes and create a new variable which remove the special characters from the datetime by importing the re library would be a lot easier:

`time_for_file_name = re.sub(r'[:+,.]',"_",time_created)`

and as well replacing the part of the code datetime.utcnow() as this is not recomended since version 3.16 and use `datetime.now(timezone.utc) `instead.

Let me know if I can get this assign and do the change.

**Comment by yozhiik** [comment]
Go ahead @IanVargas. This is my first project on github too so I am still not super familiar with how to collaborate on stuff, I've assigned this to you but apologies if I end up doing anything stupid!

**Comment by IanVargas** [comment]
hi @yozhiik np, we can colaborate together as well if anything comes up, here's my telegram info in case you want to get in contact about any kind of topic https://t.me/Poohtazo, will work on this right away, thanks!

**Comment by IanVargas** [comment]
Hi @yozhiik So I fixed the issue and created a pull request so you can test it whenever you have the time, as well for this issue I created a fork where I worked on the issue in order to not use the main repository, you can check the fork if it's easier to do the testing from there.

Essentially what i did was: 

first I implemented the extension from datetime called timezone which is the one that replaced the old one:
`from datetime import datetime,timezone`

First i created the next variables using `re.sub` in order to remove the special characters in this case ":" which were the ones not allowing the file to get created on windows and replaced them by a "." so user will now that's the time:
```
file_created_time = str(datetime.now(timezone.utc)) 
time_for_file_name = re.sub(r'[:+,.]',".",file_created_time) 
f_name = download_type + "_" + fname_address + "_" + time_for_file_name + ".csv"
```

Please let me know if you have any question or suggestion and we can go trough it together.

**Comment by yozhiik** [comment]
Thank you for being so clear! I've merged that now.
